# Generated by Django 5.2.6 on 2025-09-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Студент')], default='student', max_length=15),
        ),
    ]
